baseURL = "https://spontaneous-basbousa-cabb4e.netlify.app/"
title = "Shell"
# author = "Yukuro"
# prevent build failures when using Hugo's Instagram shortcode due to deprecated Instagram API.
# See https://github.com/gohugoio/hugo/issues/7228#issuecomment-714490456
ignoreErrors = ["error-remote-getjson"]

[Params]
  # Note: This is for the meta description, which is different from the "description" displayed in the terminal.
  description = "absolutely legendary portfolio site"
  [Params.Terminal]
  # Note: color schema
  # Note: You can choose between
  # Note: ["monokai", "powershell", "gruvbox_light", "gruvbox_dark", "solarized_light", "solarized_dark", "ubuntu", "retro"]
  # Note: If you want to use the Goph theme, set it to "goph" (See README.md)
  schema = "monokai"

  # Note: in terminal
  # [userName]@[pcName]:~/$ cd [workDir]
  # [userName]@[pcName]:~/[workDir]$ cat [profile]
  #
  # [description]
  #
  # Note: if you set Params.Tree > use = true
  # [userName]@[pcName]:~/[workDir]$ tree ./[folderName]/
  # ./[folderName]/
  # ...
  # Note: result of the tree command
  userName = "wyatt"
  pcName = "kickblip"
  workDir = "2022-23"
  profile = "bio.txt"
  profile2 = "links.txt"

  # Note: speed at which text is displayed on the terminal
  # Note: if set to 0, typing animation will be disabled
  # Note:
  # Note: if you want to enable Mathjax, you need to set it to 0
  # Note: and set "math: true" at front matter in your Markdown file
  ps1Delay = 0 # prompt speed : [userName]@[pcName]:~/$ , [userName]@[pcName]:~/[workDir]$
  stdoutDelay = 0 # stdout speed : [description] , files in Params.Tree
  commandDelay = 50 # command speed : cd [workDir] , cat [profile] , tree ./[folderName]/

  # terminalDelay = 20 : deprecated

  # Note: speed at which text is displayed on the activity pages
  # Note: if set to 0, typing animation will be disabled
  # Note: 
  # Note: if you want to enable Mathjax, you need to set it to 0
  # Note: and set "math: true" at front matter in your Markdown file
  titleDelay = 0 # title speed : "title" in front matter
  contentDelay = 0 # content speed : content in .md file

  # activityDelay = 5 : deprecated

  description = """
  Hi, I'm Wyatt Hansen
  I like machine learning and algorithms
  I'm currently a senior in high school
  I started coding in October 2022
  I'm entirely self taught
  Here's some of the projects I've worked on...
  
  """

  description2 = """
  And here's some more of my links
  if you want to learn more about me
  or get in touch

  """

  # Note: If you want to use a Markdown file, you can use the following
  # description = "/description.md"
  # Note: and put the description.md in /content/description.md

  [Params.Tree]
  use = true
  folderName = "my_portfolio"
  # Note: ["ACTIVITY", "URL or PATH TO YOUR MARKDOWN FILE"]
  files = [ 
    ["multiplayer browser based game", "https://github.com/Kickblip/launch.io"],
    ["spotify seamless transitions companion app", "https://github.com/Kickblip/knit-list/"],
    ["automated tiktok video generator", "https://github.com/IP-2023"],
    ["self driving food delivery rover", "https://github.com/Kickblip/delivery-robot"],
    ["this website", "https://github.com/Kickblip/personal-website"]
  ]

  [Params.Tree2]
  use = true
  folderName = "my_links"
  files = [ 
    ["github", "https://github.com/Kickblip/"],
    ["youtube", "https://www.youtube.com/@kickball42/"]
  ]

[module]
  [module.hugoVersion]
    extended = true
    min = "0.85.0"
